<?php
declare(strict_types=1);

return [
    'default_view' => 'inicio',
    'construction_views' => [
        'aviso-de-privacidad',
        'boletines',
        'convenios-comerciales-para-afiliados',
        'eventos',
        'institucional',
        'memoria-de-eventos',
        'proveedores-asociados',
    ],
    'titles' => [
        'inicio' => 'Inicio',
        'quienes-somos' => '¿Quiénes somos?',
        'consejo-directivo' => 'Consejo Directivo',
        'aviso-de-privacidad' => 'Aviso de Privacidad',
        'portal-amuvie' => 'Formulario de Acceso',
        'mi-perfil' => 'Mi Perfil',
        'credencial-digital' => 'Credencial Digital',
        'comentarios-de-la-nom' => 'Comentarios de la NOM',
        'biblioteca-de-documentos' => 'Biblioteca de Documentos',
        'documentos-consejo-directivo' => 'Documentos Consejo Directivo',
        'solicitud-formatos-portadas' => 'Solicitud de Formatos de Portadas',
        'directorio-asociados-extendido' => 'Directorio de Asociados Extendido',
        'aranceles' => 'Aranceles',
        'enviar-mensaje' => 'Enviar mensaje',
        'afiliate' => 'Afíliate',
        'formatos-de-portada' => 'Formatos de Portada',
        'capacitacion' => 'Capacitaciones / Eventos',
        'libro-calidad-energia-electrica' => 'Libro Calidad de Energía Eléctrica',
        'bolsa-de-trabajo' => 'Bolsa de Trabajo',
        'asociados' => 'Asociados',
        'institucional' => 'Institucional',
        'instituciones' => 'Instituciones',
        'convenios-comerciales-para-afiliados' => 'Convenios comerciales para afiliados',
        'proveedores-asociados' => 'Proveedores – Asociados',
        'contactanos' => 'Formulario de Contacto',
        'informacion' => 'Información',
        'comunicacion' => 'Comunicación',
        'eventos' => 'Eventos',
        'memoria-de-eventos' => 'Memoria de eventos',
        'boletines' => 'Boletines',
        'crecimiento-de-asociados-del-vi-consejo-directivo-2024-2026' => 'Crecimiento de Asociados del VI Consejo Directivo 2024 – 2026',
        'estadisticas-de-redes-sociales-del-vi-consejo-directivo-2024-2026' => 'Estadísticas de Redes Sociales del VI Consejo Directivo 2024 – 2026',
        'convocatoria-asamblea-extraordinaria-2026' => 'Convocatoria Asamblea extraordinaria 2026',
        'integracion-de-amuvie-al-ccnnie-e-invitacion-para-unirse-a-los-grupos-de-trabajo' => 'Integración de AMUVIE al CCNNIE e invitación para unirse a los grupos de trabajo',
        'consulta-el-programa-asamblea-general-ordinaria' => 'Consulta el Programa Asamblea General Ordinaria',
        'invitacion-del-ipn-a-participar-en-encuesta-sobre-la-infraestructura-de-la-calidad' => 'Invitación del IPN a participar en encuesta sobre la Infraestructura de la Calidad',
        'invitados-especiales-asamblea-general-ordinaria-amuvie-2025' => 'Invitados Especiales Asamblea General Ordinaria AMUVIE 2025',
        'manual-nom-001-sede-2012-edicion-especial-amuvie' => 'Manual NOM 001 SEDE 2012 – Edición Especial AMUVIE',
        'amuvie-ac-electrivallara-2025' => 'AMUVIE AC – ELECTRIVALLARA 2025',
        'souvenirs-amuvie-2025' => 'Souvenirs AMUVIE 2025',
        'asamblea-general-ordinaria-11vo-aniversario-de-la-asociacion' => 'Asamblea General Ordinaria & 11vo Aniversario de la Asociación',
        'amuvie-presente-en-la-celebracion-de-verificadores-unidos-de-mexico' => 'AMUVIE Presente en la Celebración de Verificadores Unidos de México',
        'amuvie-presente-en-la-asamblea-ordinaria-de-musica' => 'AMUVIE Presente en la Asamblea Ordinaria de Música',
        'convocatoria-a-grupo-de-trabajo-de-la-conuee' => 'Convocatoria a Grupo de Trabajo de la CONUEE',
        'atento-aviso' => 'Atento Aviso',
        'comision-ejecutiva-ema' => 'Comisión Ejecutiva EMA',
        'muchas-felicidades-ing-aquiles-manuel-lopez-marin' => '¡Muchas felicidades Ing. Aquiles Manuel López Marin!',
        'promocion-membresia-2025' => 'Promoción Membresía 2025',
        'nuevo-oficio-a-stps-para-tramites-pendientes' => 'Nuevo oficio a STPS para trámites pendientes',
    ],
];
