<?php
$safe = static fn(mixed $value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$adminNav = [
    ['dashboard','fa-tachometer-alt','Dashboard'], ['usuarios','fa-users-cog','Usuarios'],
    ['documentos','fa-folder-open','Documentos'], ['solicitudes','fa-clipboard-list','Solicitudes'],
    ['mensajes','fa-envelope-open-text','Mensajes'], ['auditoria','fa-history','Auditoría'],
];
$csrf = $safe($_SESSION['csrf_token']);
?>
<div class="member-shell admin-shell">
    <aside class="member-sidebar admin-sidebar">
        <a class="member-sidebar__logo" href="<?= $safe(site_url('administracion/')) ?>"><img src="<?= $safe(site_url('assets/images/logoamuvieblanco.png')) ?>" alt="AMUVIE A.C."></a>
        <nav>
            <?php foreach ($adminNav as [$section,$icon,$label]): ?><a href="<?= $safe(site_url('administracion/?seccion=' . $section)) ?>" class="<?= $adminSection === $section ? 'is-active' : '' ?>"><i class="fas <?= $safe($icon) ?>"></i><span><?= $safe($label) ?></span></a><?php endforeach; ?>
            <a href="<?= $safe(site_url('mi-perfil/')) ?>"><i class="fas fa-user"></i><span>Portal de asociado</span></a>
        </nav>
    </aside>
    <main class="admin-page">
        <header class="admin-heading">
            <div><p>Panel administrativo</p><h1><?= $safe(ucfirst($adminSection)) ?></h1></div>
            <form method="post"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="logout"><button type="submit"><i class="fas fa-sign-out-alt"></i> Cerrar sesión</button></form>
        </header>

        <?php if (!empty($_SESSION['user']['must_change_password'])): ?>
            <form class="admin-password-warning" method="post">
                <input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="change_own_password">
                <div><strong>Contraseña temporal activa</strong><span>Crea una contraseña definitiva de al menos 12 caracteres.</span></div>
                <input type="password" name="password" minlength="12" autocomplete="new-password" required><button type="submit">Actualizar contraseña</button>
            </form>
        <?php endif; ?>
        <?php if ($adminError): ?><p class="admin-alert admin-alert--error" role="alert"><?= $safe($adminError) ?></p><?php endif; ?>
        <?php if ($adminSuccess): ?><p class="admin-alert admin-alert--success" role="status"><?= $safe($adminSuccess) ?></p><?php endif; ?>

        <?php if ($adminSection === 'dashboard'): ?>
            <section class="admin-stats" aria-label="Resumen del portal">
                <?php foreach ([['users','fa-users','Usuarios'],['active_users','fa-user-check','Usuarios activos'],['documents','fa-file-alt','Documentos activos'],['requests','fa-clipboard-list','Solicitudes pendientes'],['messages','fa-envelope','Mensajes pendientes']] as [$key,$icon,$label]): ?>
                    <article><i class="fas <?= $icon ?>"></i><strong><?= (int) $adminCounts[$key] ?></strong><span><?= $safe($label) ?></span></article>
                <?php endforeach; ?>
            </section>
            <section class="admin-card"><h2>Acciones rápidas</h2><div class="admin-quick-links"><a href="<?= $safe(site_url('administracion/?seccion=documentos')) ?>"><i class="fas fa-upload"></i> Subir documento</a><a href="<?= $safe(site_url('administracion/?seccion=usuarios')) ?>"><i class="fas fa-user-plus"></i> Crear usuario</a><a href="<?= $safe(site_url('administracion/?seccion=solicitudes')) ?>"><i class="fas fa-tasks"></i> Revisar solicitudes</a></div></section>

        <?php elseif ($adminSection === 'usuarios'): ?>
            <section class="admin-card"><h2>Crear usuario</h2><form class="admin-form admin-form--grid" method="post"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="create_user"><label>Usuario<input name="username" minlength="3" maxlength="50" required></label><label>Nombre completo<input name="full_name" maxlength="150"></label><label>Correo<input type="email" name="email" required></label><label>Contraseña temporal<input type="password" name="password" minlength="12" required></label><label>Rol<select name="role"><option value="usuario">Usuario</option><option value="editor">Editor</option><option value="administrador">Administrador</option></select></label><button type="submit">Crear usuario</button></form></section>
            <section class="admin-card"><h2>Usuarios registrados</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Usuario</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Último acceso</th><th>Acciones</th></tr></thead><tbody><?php foreach ($adminUsers as $user): $primaryRole = in_array('administrador',$user['roles'],true)?'administrador':(in_array('editor',$user['roles'],true)?'editor':'usuario'); ?><tr><td><strong><?= $safe($user['username']) ?></strong><small><?= $safe($user['full_name']) ?></small></td><td><?= $safe($user['email']) ?></td><td><?= $safe(implode(', ', $user['roles'])) ?></td><td><span class="admin-status admin-status--<?= $safe($user['status']) ?>"><?= $safe($user['status']) ?></span></td><td><?= $safe($user['last_login_at'] ?: 'Sin acceso') ?></td><td><div class="admin-actions"><form method="post"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="update_user"><input type="hidden" name="user_id" value="<?= (int) $user['id'] ?>"><input name="full_name" value="<?= $safe($user['full_name']) ?>" placeholder="Nombre completo"><input type="email" name="email" value="<?= $safe($user['email']) ?>" required><select name="role"><?php foreach(['usuario','editor','administrador'] as $role): ?><option value="<?= $role ?>" <?= $primaryRole===$role?'selected':'' ?>><?= ucfirst($role) ?></option><?php endforeach; ?></select><button type="submit">Editar</button></form><form method="post"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="user_status"><input type="hidden" name="user_id" value="<?= (int) $user['id'] ?>"><select name="status"><option value="activo">Activo</option><option value="inactivo">Inactivo</option><option value="bloqueado">Bloqueado</option></select><button type="submit">Aplicar</button></form><form method="post"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="reset_password"><input type="hidden" name="user_id" value="<?= (int) $user['id'] ?>"><input type="password" name="password" minlength="12" placeholder="Contraseña temporal" required><button type="submit">Restablecer</button></form><?php if ((int) $user['id'] !== (int) $sessionUser['id']): ?><form method="post" data-confirm="¿Eliminar permanentemente al usuario <?= $safe($user['username']) ?>? Esta acción no se puede deshacer."><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="delete_user"><input type="hidden" name="user_id" value="<?= (int) $user['id'] ?>"><button class="admin-danger-button" type="submit"><i class="fas fa-trash-alt" aria-hidden="true"></i> Eliminar usuario</button></form><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div></section>

        <?php elseif ($adminSection === 'documentos'): ?>
            <section class="admin-card"><h2>Subir documento</h2><form class="admin-form admin-form--grid" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="upload_document"><label>Título<input name="title" maxlength="255" required></label><label>Categoría<select name="category_id" required><option value="">Selecciona una categoría</option><?php foreach ($adminCategories as $category): ?><option value="<?= (int) $category['id'] ?>"><?= $safe($category['name']) ?></option><?php endforeach; ?></select></label><label class="admin-form__wide">Descripción<textarea name="description" rows="3"></textarea></label><label class="admin-form__wide">Archivo<input type="file" name="document" accept=".pdf,.doc,.docx,.xls,.xlsx" required><small>PDF, Word o Excel; máximo 20 MB.</small></label><button type="submit">Subir documento</button></form></section>
            <section class="admin-card"><h2>Catálogo administrado</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Documento</th><th>Categoría</th><th>Tamaño</th><th>Estado</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody><?php foreach ($adminDocuments as $document): ?><tr><td><a href="<?= $safe(site_url($document['stored_path'])) ?>" target="_blank" rel="noopener"><?= $safe($document['title']) ?></a><small><?= $safe($document['original_name']) ?></small></td><td><?= $safe($document['category_name']) ?></td><td><?= number_format((int) $document['file_size']/1048576, 2) ?> MB</td><td><span class="admin-status admin-status--<?= $safe($document['status']) ?>"><?= $safe($document['status']) ?></span></td><td><?= $safe($document['created_at']) ?></td><td><div class="admin-actions"><form method="post"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="update_document"><input type="hidden" name="document_id" value="<?= (int) $document['id'] ?>"><input name="title" value="<?= $safe($document['title']) ?>" required><input name="description" value="<?= $safe($document['description']) ?>" placeholder="Descripción"><select name="category_id"><?php foreach($adminCategories as $category): ?><option value="<?= (int)$category['id'] ?>" <?= (int)$document['category_id']===(int)$category['id']?'selected':'' ?>><?= $safe($category['name']) ?></option><?php endforeach; ?></select><button type="submit">Editar</button></form><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="replace_document"><input type="hidden" name="document_id" value="<?= (int) $document['id'] ?>"><input type="file" name="document" accept=".pdf,.doc,.docx,.xls,.xlsx" required><button type="submit">Reemplazar</button></form><form method="post"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="document_status"><input type="hidden" name="document_id" value="<?= (int) $document['id'] ?>"><input type="hidden" name="status" value="<?= $document['status'] === 'activo' ? 'inactivo' : 'activo' ?>"><button type="submit"><?= $document['status'] === 'activo' ? 'Desactivar' : 'Activar' ?></button></form></div></td></tr><?php endforeach; ?></tbody></table></div></section>

        <?php elseif ($adminSection === 'solicitudes'): ?>
            <section class="admin-card"><h2>Solicitudes de formatos</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Folio</th><th>Usuario</th><th>Solicitante</th><th>Formatos</th><th>Total</th><th>Estado</th></tr></thead><tbody><?php foreach ($adminRequests as $request): ?><tr><td>#<?= (int) $request['id'] ?><small><?= $safe($request['created_at']) ?></small></td><td><?= $safe($request['username']) ?></td><td><?= $safe($request['applicant_name']) ?></td><td><?= $safe(implode(', ', json_decode($request['selected_formats'], true) ?: [])) ?></td><td>$<?= number_format((float) $request['total'], 2) ?></td><td><form method="post" class="admin-inline-form"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="request_status"><input type="hidden" name="request_id" value="<?= (int) $request['id'] ?>"><select name="status"><?php foreach (['recibida','en_revision','atendida','cancelada'] as $status): ?><option value="<?= $status ?>" <?= $request['status']===$status?'selected':'' ?>><?= $safe($status) ?></option><?php endforeach; ?></select><button type="submit">Guardar</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>

        <?php elseif ($adminSection === 'mensajes'): ?>
            <section class="admin-card"><h2>Mensajes de asociados</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Folio</th><th>Remitente</th><th>Categoría</th><th>Mensaje</th><th>Estado</th></tr></thead><tbody><?php foreach ($adminMessages as $message): ?><tr><td>#<?= (int) $message['id'] ?><small><?= $safe($message['created_at']) ?></small></td><td><?= $safe($message['first_name'].' '.$message['last_name']) ?><small><?= $safe($message['email']) ?></small></td><td><?= $safe($message['category']) ?></td><td class="admin-message-cell"><?= nl2br($safe($message['message'])) ?></td><td><form method="post" class="admin-inline-form"><input type="hidden" name="csrf_token" value="<?= $csrf ?>"><input type="hidden" name="action" value="message_status"><input type="hidden" name="message_id" value="<?= (int) $message['id'] ?>"><select name="status"><?php foreach (['recibido','en_revision','respondido','cerrado'] as $status): ?><option value="<?= $status ?>" <?= $message['status']===$status?'selected':'' ?>><?= $safe($status) ?></option><?php endforeach; ?></select><button type="submit">Guardar</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>

        <?php else: ?>
            <section class="admin-card"><h2>Registro de actividad</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Fecha</th><th>Administrador</th><th>Acción</th><th>Entidad</th><th>Detalles</th></tr></thead><tbody><?php foreach ($adminActivity as $activity): ?><tr><td><?= $safe($activity['created_at']) ?></td><td><?= $safe($activity['username']) ?></td><td><?= $safe($activity['action']) ?></td><td><?= $safe($activity['entity_type']) ?><?= $activity['entity_id'] ? ' #'.(int)$activity['entity_id'] : '' ?></td><td><?= $safe($activity['details']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
        <?php endif; ?>
        <footer class="member-footer">Copyright © <?= date('Y') ?> Asociación Mexicana de Unidades de Verificación, Inspección y Estandarización AC.</footer>
    </main>
</div>
